In [1]:
import numpy as np

1.Створіть одновимірний масив (вектор) з добутками парних чисел на їхні попередні непарні числа, починаючи з 2, та виведіть його значення. 

In [2]:
n = 10

# Створюємо вектор, використовуючи NumPy
vector = np.zeros(n)

# Заповнюємо вектор значеннями
for i in range(1, n):
    # Парні числа
    if i % 2 == 0:
        vector[i] = i * (i - 1)  # Добуток парного числа на його попереднє непарне число

# Виводимо значення вектора
print(vector)

[ 0.  0.  2.  0. 12.  0. 30.  0. 56.  0.]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів відстаней між кожною парою натуральних чисел, починаючи з 1, та виведіть його значення. 

In [3]:

# Створюємо двовимірний масив, використовуючи NumPy
matrix = np.zeros((3, 3))

# Заповнюємо матрицю значеннями квадратів відстаней між кожною парою чисел
for i in range(n):
    for j in range(n):
        # Використовуємо квадрат відстані між (i+1) та (j+1)
        matrix[i, j] = (i + 1 - (j + 1)) ** 2

# Виводимо значення матриці
print(matrix)

[[0. 1. 4.]
 [1. 0. 1.]
 [4. 1. 0.]]


3.Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від -2 до 2 та знайдіть середнє за модулем значення його елементів. 

In [4]:
matrix = np.random.uniform(-2, 2, size=(5, 5))

# Знаходимо середнє за модулем значення елементів матриці
average_absolute_value = np.mean(np.abs(matrix))

# Виводимо матрицю та середнє за модулем значення елементів
print("Матриця:")
print(matrix)
print("\nСереднє за модулем значення елементів:", average_absolute_value)

Матриця:
[[-0.97081043 -0.55855642 -1.4444811  -1.34274959 -1.77347498]
 [ 0.16260323 -0.79975373  1.36431653 -0.25446571 -0.04701544]
 [-1.02601987  0.61138723 -1.87444467  0.16893297  1.7220488 ]
 [-1.2643815   0.92843902  0.27847798  1.54788544 -1.44334821]
 [-1.25775094  1.53140811 -1.81317372  0.82715079  0.11955418]]

Середнє за модулем значення елементів: 1.0053052245756136


4.Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення. 

In [5]:

matrix = np.random.rand(5, 5)

# Знаходимо середнє значення елементів матриці
average_value = np.mean(matrix)

# Знаходимо елементи, які менше середнього значення
less_than_average = matrix[matrix < average_value]

# Знаходимо суму цих елементів
sum_less_than_average = np.sum(less_than_average)

# Виводимо матрицю та результат
print("Матриця:")
print(matrix)
print("\nСереднє значення елементів:", average_value)
print("Сума елементів, які менше середнього значення:", sum_less_than_average)


Матриця:
[[0.73863984 0.53599974 0.33337451 0.14237889 0.00963326]
 [0.57147541 0.5686987  0.35569204 0.80141927 0.45651973]
 [0.67343908 0.25411939 0.63667121 0.3755303  0.35118972]
 [0.70655001 0.32247275 0.63995738 0.74648565 0.75509484]
 [0.24308691 0.15529088 0.24517486 0.4239363  0.4400009 ]]

Середнє значення елементів: 0.4593132633106509
Сума елементів, які менше середнього значення: 4.108400460327712


5.Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання ta множення. 

In [6]:
array1 = np.random.uniform(-2, 2, 7)
array2 = np.random.uniform(-2, 2, 7)

# Виконуємо поелементні операції
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

# Виводимо вихідні масиви та результати операцій
print("Масив 1:", array1)
print("Масив 2:", array2)
print("\nРезультат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)


Масив 1: [-0.84248293  1.2022405   0.50326513  1.25164689  1.730623   -0.81942983
  1.72390168]
Масив 2: [-1.20776932 -0.83745228  0.0600529  -0.74601052 -1.49957228  0.26993791
 -0.04703394]

Результат додавання: [-2.05025225  0.36478822  0.56331802  0.50563637  0.23105071 -0.54949192
  1.67686774]
Результат віднімання: [ 0.36528639  2.03969278  0.44321223  1.99765741  3.23019528 -1.08936774
  1.77093562]
Результат множення: [ 1.01752504 -1.00681905  0.03022253 -0.93374175 -2.59519427 -0.22119517
 -0.08108189]


6.Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [7]:
vector1 = np.random.randint(-10, 10, 7)
vector2 = np.random.randint(-10, 10, 7)

# Знаходимо скалярний добуток векторів
dot_product_result = np.dot(vector1, vector2)

# Виводимо вихідні вектори та результат скалярного добутку
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("\nРезультат скалярного добутку:", dot_product_result)


Вектор 1: [ -1   5  -3   1 -10   6   8]
Вектор 2: [ 6 -1 -5  3  8  0  2]

Результат скалярного добутку: -57


7.Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою. 

In [8]:

matrix1 = np.random.randint(1, 13, size=(4, 2))
matrix2 = np.random.randint(1, 13, size=(2, 5))

# Перемножуємо матриці
result_matrix = np.dot(matrix1, matrix2)

# Виводимо вихідні матриці та результат перемноження
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nРезультат перемноження:")
print(result_matrix)


Матриця 1:
[[11  9]
 [ 9  4]
 [11  1]
 [ 3 12]]

Матриця 2:
[[ 8  2  9  6  1]
 [12  4 12  6  4]]

Результат перемноження:
[[196  58 207 120  47]
 [120  34 129  78  25]
 [100  26 111  72  15]
 [168  54 171  90  51]]


8.Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю. 

In [9]:
matrix = np.random.randint(1, 11, size=(2, 2))

# Перевіряємо, чи матриця є оберненою (детермінант не дорівнює нулю)
det = np.linalg.det(matrix)

if det != 0:
    # Знаходимо обернену матрицю
    inverse_matrix = np.linalg.inv(matrix)

    # Виводимо вихідну матрицю та обернену матрицю
    print("Матриця:")
    print(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця не має оберненої матриці (детермінант дорівнює нулю).")


Матриця:
[[3 2]
 [8 8]]

Обернена матриця:
[[ 1.    -0.25 ]
 [-1.     0.375]]


9.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 10 до 50 та транспонуйте її. 

In [10]:
matrix = np.random.uniform(10, 50, size=(3, 3))

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо вихідну матрицю та транспоновану матрицю
print("Матриця:")
print(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця:
[[49.527547   28.68142097 43.57363662]
 [31.60678793 39.1055875  26.28680446]
 [42.82253801 45.8293168  39.51216635]]

Транспонована матриця:
[[49.527547   31.60678793 42.82253801]
 [28.68142097 39.1055875  45.8293168 ]
 [43.57363662 26.28680446 39.51216635]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть середнє значення елементів вектору. 

In [11]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4)

# Знаходимо середнє значення елементів вектору
average_value = np.mean(vector)

# Виводимо вихідну матрицю та вектор, а також середнє значення елементів вектору
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nСереднє значення елементів вектору:", average_value)


Матриця:
[[10  5  9  1]
 [ 7  8  3  7]
 [ 7  7  5  5]]

Вектор:
[0.99374688 0.37428973 0.95772677 0.45424202]

Середнє значення елементів вектору: 0.6950013523990053


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму елементів вектору, які більше за відповідний елемент матриці. 

In [13]:

matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, size=3)

# Знаходимо суму елементів вектору, які більше за відповідний елемент матриці
sum_greater_elements = np.sum(vector[vector > np.max(matrix)])

# Виводимо вихідну матрицю та вектор, а також суму елементів вектору, які більше за відповідний елемент матриці
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nСума елементів вектору, які більше за відповідний елемент матриці:", sum_greater_elements)



Матриця:
[[0.92726177 0.46918342 0.49201182]
 [0.29895923 0.29012546 0.34577076]]

Вектор:
[ 4 10  8]

Сума елементів вектору, які більше за відповідний елемент матриці: 22


12.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток елементів діагоналі першої матриці. 

In [15]:
matrix1 = np.random.randint(1, 11, size=(4, 4))

# Знаходимо добуток елементів діагоналі першої матриці
diagonal_product = np.prod(np.diag(matrix1))

# Виводимо вихідну матрицю та добуток елементів діагоналі
print("Матриця 1:")
print(matrix1)
print("\nДобуток елементів діагоналі першої матриці:", diagonal_product)


Матриця 1:
[[10  5  5  8]
 [ 2 10  2  7]
 [ 1  2  1  7]
 [ 9  4  4  7]]

Добуток елементів діагоналі першої матриці: 700


13.Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів. 

In [16]:
matrix1 = np.random.uniform(-1, 1, size=(3, 3))
matrix2 = np.random.uniform(-1, 1, size=(3, 3))

# Знаходимо суму елементів обох матриць
sum_of_matrices = np.sum(matrix1) + np.sum(matrix2)

# Виводимо матриці та суму їх елементів
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nСума елементів обох матриць:", sum_of_matrices)


Матриця 1:
[[ 0.36114429  0.18434629  0.00603106]
 [ 0.3790064  -0.85371768 -0.6289173 ]
 [ 0.12438197 -0.35806728  0.95274676]]

Матриця 2:
[[-0.85857823 -0.98268746 -0.5439639 ]
 [ 0.43878123  0.00283457 -0.86259677]
 [-0.56419867  0.38778667 -0.8321667 ]]

Сума елементів обох матриць: -3.6478347334425503


14.Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найбільший елемент матриці.

In [17]:
matrix = np.random.uniform(-10, 10, size=(6, 6))

# Знаходимо найбільший елемент матриці
max_element = np.max(matrix)

# Виводимо матрицю та найбільший елемент
print("Матриця:")
print(matrix)
print("\nНайбільший елемент матриці:", max_element)


Матриця:
[[-1.69182928 -7.72246257  3.35392848 -9.34530653 -7.55882306  9.39177835]
 [ 0.97641732 -1.12964782 -4.78374685  3.42889454  4.72935779  0.18268941]
 [ 5.68915149 -5.53985065  8.30407748 -6.65226809  4.76138392  1.40143365]
 [-8.40070595 -5.49520793  4.3176724  -0.18263516  4.33578769  6.98602666]
 [-9.65139752  0.21483657 -5.14481375 -2.82363562  7.12611284  5.0102248 ]
 [ 7.74939903  3.96881382 -8.02309435  7.38901845 -6.62819781  4.09317088]]

Найбільший елемент матриці: 9.391778349830219


15.Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить кількість нульових елементів в кожному рядку матриці. 

In [18]:
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))
# Знаходимо вектор-стовпчик кількості нульових елементів в кожному рядку матриці
zero_count_vector = np.sum(matrix == 0, axis=1).reshape(-1, 1)

# Виводимо матрицю та вектор-стовпчик
print("Матриця:")
print(matrix)
print("\nВектор-стовпчик кількості нульових елементів в кожному рядку:")
print(zero_count_vector)


Матриця:
[[-0.04580341 -0.01564273 -0.14465969  0.00163116  0.16450326]
 [ 0.13849442  0.23840567  0.18111308 -0.00797195 -0.17959012]
 [-0.41306435 -0.49523474  0.26570964 -0.40742883 -0.17741018]
 [ 0.14752503 -0.28403056 -0.15190798 -0.13871907  0.27793244]
 [ 0.13999132  0.18360463  0.28992133 -0.10882998 -0.49017354]]

Вектор-стовпчик кількості нульових елементів в кожному рядку:
[[0]
 [0]
 [0]
 [0]
 [0]]
